version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./sites/{SITE_NAME}/wordpress:/var/www/html
    depends_on:
      - php


  php:
    image: php:latest
    volumes:
      - ./sites/{SITE_NAME}/wordpress:/var/www/html

  wordpress:
    image: wordpress:latest
